### ISSUE TITLE
Adding Nimbus repository to pom.xml to support Jenkins build

### ISSUE THREAD

**Issue by jhrabi** [admpresales/uftdev-aos-web-gherkin#5]
@panama69 Currently, I'm injecting the repositories for Nimbus through the settings.xml in Jenkins. My question is, does it make more sense to directly add the repository information into the pom file? That way, running the test would be the same regardless of whether we were running it from intellij or jenkins (there'd be nothing under the covers on Jenkins side). The other benefit is if the dependencies were already inside the devops container, then intellij wouldn't need to download it from central, it could download it directly from the devops container.

Curious as to your thoughts.

**Comment by panama69** [comment]
**Does it make more sense to directly add the repository information into the pom file?**
How would this affect people when they create a new project?  Would we need to teach them how to modify the pom?  If so, then I would not want presales to have to remember how to modify the pom file when they create a new test in front of a customer.

**Comment by jhrabi** [comment]
@panama69 So my primary concern was that the SAs were going to need to learn how to configure their Jenkins jobs if they wanted to make new ones to use the settings.xml that was being provided by Jenkins. However, it looks like Jenkins can be changed to modify the default settings.xml that is used for every project. This would mean that if the SAs were creating new jobs in Jenkins, the configuration would already be done for them under the covers. So I will close this.
